---
title: "p8105_hw2_abj2136"
output: github_document
date: "2026-10-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Installing libraries
```{r message = FALSE}
library(tidyverse)
library(readxl)
```


# Problem 2

## Mr Trash Wheel
```{r}
# Looking at the sheets in the file
excel_sheets("202610 Trash Wheel Collection Data.xlsx")

#importing and cleaning the the mr trash wheel dataset

mr_trash_df = read_excel("202610 Trash Wheel Collection Data.xlsx",
                      sheet = "Mr. Trash Wheel",
                      range = "A2:N742",
                      na = c("","NA", ".")
                      ) |>
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(sports_balls = as.integer(round(sports_balls))) |> 
  mutate(year = as.integer(year))
  
  # used glimpse in the console to determine variable types for all three data frames to 
  # determine which variables were entered as characters vs numeric values. In Mr.Trash 
  # the year variable needed to be converted to an integer, and in Professor trash the 
  # plastic bottles variable needed to be converted to numeric. 
```

## Professor Trash Wheel
```{r}
#importing and cleaning the the prof trash wheel dataset

prof_trash_df = read_excel("202610 Trash Wheel Collection Data.xlsx",
                      sheet = "Professor Trash Wheel",
                      range = "A2:M139",
                      na = c("","NA", ".")
                      ) |>
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(plastic_bottles = as.numeric(plastic_bottles))
```

## Gwynnda the Good Wheel of the West
```{r}
#importing and cleaning the the prof trash wheel dataset

gwynnda_df = read_excel("202610 Trash Wheel Collection Data.xlsx",
                      sheet = "Gwynnda the Good Wheel of the W",
                      range = "A2:L394",
                      na = c("","NA", ".")
                      ) |>
  janitor::clean_names() |> 
  drop_na(dumpster)
```

# Merging datasets
```{r}
# creating a trash_wheel variable to keep track of which trash wheel is which after merging

mr_trash_df = mr_trash_df |> 
  mutate(trash_wheel = "Mr. Trash Wheel")

prof_trash_df = prof_trash_df |> 
  mutate(trash_wheel = "Professor Trash Wheel")

gwynnda_df = gwynnda_df |> 
  mutate(trash_wheel = "Gwynnda the Good Wheel of the W")

# merging the datasets

combined_trash_df = 
  bind_rows(
    mr_trash_df,
    prof_trash_df,
    gwynnda_df, 
  )


```



